encryptionsalt: v1:lCa+LvoBS8k=:v1:4ljpDTsgxoX6+bwo:mn1Wqu5YehgsPWEe1odiOuxrZJ5DVA==
config:
  appservice:size: B1
  appservice:tier: Basic
  azure-native:environment: public
  azure-native:location: WestEurope
  azure:environment: public
  azure:location: WestEurope
  azureactivedirectory:clientid: 00000000-0000-0000-0000-000000000000
  azureactivedirectory:domain: <aad>.onmicrosoft.com
  azureactivedirectory:tenantId: 00000000-0000-0000-0000-000000000000
  containerregistry:sku: Basic
  iothub:name: S1
  keyvault:sku: standard
  project:environment: dev
  project:productName: webapi
  servicebus:sku: basic
  sqlserver:edition: Basic
  sqlserver:password:
    secure: v1:znHPaIxTcM625X/d:JUMNva+3tsBI3u9w7aVRRBdl8+A2EcaYy+9io1IAPDSKxxcnGws=
  sqlserver:serviceObjectiveName: Basic
