parameters:
  - name: dependsOn
    type: string
    default: Build

  - name: deploymentJobs
    type: deploymentList

  - name: environments
    type: object
    default:
      dev:
        name: Development
        locations:
          euw: West Europe
        jobs: []
        deploymentJobs: []
      prev:
        name: Preview
        dependsOn: dev
        locations:
          euw: West Europe
        jobs: []
        deploymentJobs: []
      prod:
        name: Production
        dependsOn: prev
        locations:
          euw: West Europe
        jobs: []
        deploymentJobs: []

stages:
  - ${{ each env in parameters.environments }}:
      - ${{ each loc in env.value.locations }}:
          - stage: ${{ env.key }}_${{ loc.key }}
            displayName: ${{ env.value.name }} ${{ loc.value }}
            ${{ if ne(env.value.dependsOn, '') }}:
              dependsOn: ${{ env.value.dependsOn }}_${{ loc.key }}
            ${{ if eq(env.value.dependsOn, '') }}:
              dependsOn: ${{ parameters.dependsOn }}
            variables:
              - name: Environment
                value: ${{ env.key }}
              - name: EnvironmentName
                value: ${{ env.value.name }}
              - name: Location
                value: ${{ loc.key }}
              - name: LocationName
                value: ${{ loc.value }}
              - template: /eng/templates/azure-variables.yml
            jobs:
              - ${{ each job in parameters.deploymentJobs }}:
                  - deployment: ${{ job.deployment }}_${{ env.key }}_${{ loc.key }}
                    displayName: ${{ job.displayName }} ${{ env.value.name }} ${{ loc.value }}
                    workspace:
                      clean: all
                    # use a different environment for resource triggers so we can have different approvals
                    ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
                      environment: Deployment_PullRequest_${{ env.key }}_${{ loc.key }}
                    ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
                      environment: Deployment_${{ env.key }}_${{ loc.key }}
                    ${{ each pair in job }}:
                      ${{ if and(ne(pair.key, 'dependsOn'), ne(pair.key, 'displayName')) }}:
                        ${{ pair.key }}: ${{ pair.value }}
                    # ${{ each pair in job }}:
                    #   ${{ if and(ne(pair.key, 'workspace'), ne(pair.key, 'displayName'), ne(pair.key, 'environment')) }}:
                    #     ${{ pair.key }}: ${{ pair.value }}
              # - ${{ each job in env.value.jobs }}:
              #     - job: ${{ job.key }}_${{ env.key }}_${{ loc.key }}
              #       displayName: ${{ job.displayName }} ${{ env.value.name }} ${{ loc.value }}
              #       # ${{ each pair in job }}:
              #       #   ${{ if and(ne(pair.key, 'dependsOn'), ne(pair.key, 'displayName')) }}:
              #       #     ${{ pair.key }}: ${{ pair.value }}
              #       dependsOn:
              #         - ${{ if job.dependsOn }}:
              #             - ${{ format('{0}_{1}_{2}', job.dependsOn, env.key, loc.key) }}
