parameters:
  - name: dependsOn
    type: string
    default: Build

  - name: environments
    type: object
    default:
      dev:
        name: Development
        locations:
          euw: West Europe
        jobs: []
      prev:
        name: Preview
        dependsOn: dev
        locations:
          euw: West Europe
        jobs: []
      prod:
        name: Production
        dependsOn: prev
        locations:
          euw: West Europe
        jobs: []

stages:
  - ${{ each env in parameters.environments }}:
      - ${{ each loc in env.value.locations }}:
          - stage: ${{ env.key }}_${{ loc.key }}
            displayName: ${{ env.value.name }} ${{ loc.value }}
            ${{ if ne(env.value.dependsOn, '') }}:
              dependsOn: ${{ env.value.dependsOn }}_${{ loc.key }}
            ${{ if eq(env.value.dependsOn, '') }}:
              dependsOn: ${{ parameters.dependsOn }}
            variables:
              environment: ${{ env.key }}
              environmentName: ${{ env.value.name }}
              location: ${{ loc.key }}
              locationName: ${{ loc.value }}
            jobs:
              - ${{ parameter.jobs }}
