parameters:
  - name: azureSubscriptionName
    type: string

  - name: azureProductName
    type: string

  - name: environment
    type: object
    default:
      key: dev
      name: Development

  - name: location
    type: object
    default:
      key: euw
      name: West Europe

  - name: artifact
    type: object
    default:
      name: Artifact
      directory: $(Pipeline.Workspace)

jobs:
  - deployment: Deployment_Website_${{ parameters.environment.key }}_${{ parameters.location.key }}
    displayName: Deployment Website
    workspace:
      clean: all
    # use a different environment for resource triggers so we can have different approvals
    ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
      environment: Deployment_PullRequest_${{ parameters.environment.key }}_${{ parameters.location.key }}
    ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
      environment: Deployment_${{ parameters.environment.key }}_${{ parameters.location.key }}
    variables:
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        artifactName: $(Pipeline.Workspace)/${{ format('build/{0}', coalesce(parameters.artifact.name, 'Artifact')) }}
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        artifactName: $(Pipeline.Workspace)/${{ coalesce(parameters.artifact.name, 'Artifact') }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureFileCopy@4
              inputs:
                azureSubscription: ${{ parameters.azureSubscriptionName }}
                SourcePath: '$(artifactName)/*'
                Destination: AzureBlob
                storage: ${{ parameters.azureProductName }}${{ parameters.environment.key }}${{ parameters.location.key }}swstg
                ContainerName: $web
                sasTokenTimeOutInMinutes: 30
