parameters:
  - name: azureSubscriptionName
    type: string

  - name: azureProductName
    type: string

  - name: environment
    type: object
    default:
      key: dev
      name: Development

  - name: location
    type: object
    default:
      key: euw
      name: West Europe

  - name: artifact
    type: object
    default:
      name: Artifact
      directory: $(Pipeline.Workspace)/build

jobs:
  - deployment: Deployment_WebApp_${{ parameters.environment.key }}_${{ parameters.location.key }}
    displayName: Deployment Web App
    workspace:
      clean: all
    # use a different environment for resource triggers so we can have different approvals
    ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
      environment: Deployment_PullRequest_${{ parameters.environment.key }}_${{ parameters.location.key }}
    ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
      environment: Deployment_${{ parameters.environment.key }}_${{ parameters.location.key }}
    variables:
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        artifactPath: ${{ format('{0}/build/{1}', coalesce(parameters.artifact.directory, variables['Pipeline.Workspace']), coalesce(parameters.artifact.name, 'Artifact'))) }}
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        artifactPath: ${{ format('{0}/{1}', coalesce(parameters.artifact.directory, variables['Pipeline.Workspace']), coalesce(parameters.artifact.name, 'Artifact'))) }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: ArchiveFiles@2
              displayName: Archive web app
              inputs:
                rootFolderOrFile: ${{ variables.artifactPath }}
                includeRootFolder: false
                archiveType: zip
                archiveFile: ${{ variables.artifactPath }}.zip
                replaceExistingArchive: true

            - task: AzureWebApp@1
              displayName: Deploy web app
              inputs:
                azureSubscription: ${{ parameters.azureSubscriptionName }}
                appType: webApp
                appName: ${{ parameters.azureProductName }}-${{ parameters.environment.key }}-${{ parameters.location.key }}-app
                resourceGroupName: ${{ parameters.azureProductName }}-${{ parameters.environment.key }}-${{ parameters.location.key }}-rg
                package: ${{ variables.artifactPath }}.zip
                deploymentMethod: zipDeploy
                deployToSlotOrASE: false
