parameters:
  - name: shouldTest
    type: boolean
    default: true

stages:
  - stage: Build
    # always build for master except if it is a resource trigger (e.g. already build with the build pipeline)
    condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'ResourceTrigger'))
    jobs:
      - template: build/build-website.yml
        parameters:
          shouldTest: ${{ parameters.shouldTest }}
