# triggered by PR build validation
trigger: none

variables:
  - template: /eng/templates/version.yml
    parameters:
      major: 1
      minor: 0
  - template: /eng/templates/azure-variables.yml

name: $(Version)

stages:
  - template: /eng/templates/deployment/pulumi-preview-deployment.yml
    parameters:
      azureSubscriptionName: $(azureSubscriptionName)
      environment:
        key: dev
        name: Development
