parameters:
  - name: environment
    type: object
    default:
      key: dev
      name: Development

jobs:
  - template: /eng/templates/deployment/pulumi-deployment.yml
    parameters:
      azureSubscriptionName: $(azureSubscriptionName)
      environment: ${{ parameters.environment }}
      location:
        key: euw
        name: West Europe
