stages:
  # - stage: Dev_Preview
  #   displayName: Development (Preview)
  #   jobs:
  #     - template: /eng/infrastructure/preview-env.yml
  #       parameters:
  #         environment:
  #           key: dev
  #           name: Development

  - stage: Dev
    displayName: Development
    jobs:
      - template: /eng/infrastructure/deployment-env.yml
        parameters:
          environment:
            key: dev
            name: Development

  - stage: Prev_Preview
    displayName: Preview (Preview)
    jobs:
      - template: /eng/infrastructure/preview-env.yml
        parameters:
          environment:
            key: prev
            name: Preview

  - stage: Prev
    displayName: Preview
    jobs:
      - template: /eng/infrastructure/deployment-env.yml
        parameters:
          environment:
            key: prev
            name: Preview

  - stage: Prod_Preview
    displayName: Production (Preview)
    jobs:
      - template: /eng/infrastructure/preview-env.yml
        parameters:
          environment:
            key: prod
            name: Production

  - stage: Prod
    displayName: Production
    jobs:
      - template: /eng/infrastructure/deployment-env.yml
        parameters:
          environment:
            key: prod
            name: Production
