stages:
  - template: /eng/templates/deployment/locations-deployment.yml
    parameters:
      dependsOn: Build
      deploymentJobs:
        - template: /eng/webapi/deployment/deployment-env.yml
      environments:
        dev:
          name: Development
          locations:
            euw: West Europe
          jobs: []
          deploymentJobs:
            - template: /eng/webapi/deployment/deployment-env.yml

        prev:
          name: Preview
          dependsOn: dev
          locations:
            euw: West Europe
          jobs: []
          deploymentJobs:
            - template: /eng/webapi/deployment/deployment-env.yml

        prod:
          name: Production
          dependsOn: prev
          locations:
            euw: West Europe
          jobs: []
          deploymentJobs:
            - template: /eng/webapi/deployment/deployment-env.yml
