trigger:
  batch: false
  branches:
    include:
      - master
  paths:
    include:
      - src/*

variables:
  - template: ../templates/version.yml
    parameters:
      major: 1
      minor: 0
  - template: ../templates/azure-variables.yml

resources:
  pipelines:
    - pipeline: build
      source: WebApi.Build
      trigger:
        stages:
          - Build

name: $(Version)

stages:
  - template: build.yml

  - template: deployment.yml
