jobs:
  - template: /eng/templates/deployment/webapp-deployment.yml
    parameters:
      azureSubscriptionName: $(AzureSubscriptionName)
      azureProductName: $(AzureProductName)
      environment:
        key: $(Environment)
        name: $(EnvironmentName)
      location:
        key: $(Location)
        name: $(LocationName)
      artifact:
        name: WebApi
