parameters:
  - name: Environment
    type: string

  - name: EnvironmentName
    type: string

  - name: Locations
    type: object
    default:
      euw: West Europe

  - name: ArtifactDirectory
    type: string
    default: $(Pipeline.Workspace)/build

  - name: ArtifactName
    type: string
    default: Artifact

stages:
  - ${{ each pair in parameters.Locations }}:
      - stage: ${{ parameters.Environment }}_${{ pair.key }}
        displayName: ${{ parameters.Environment.Name }} ${{ pair.value }}
        variables:
          - name: ArtifactDirectory
            value: ${{ parameters.ArtifactDirectory }}

          - template: ../templates/azure-variables.yml
        jobs:
          - deployment: Deployment_${{ parameters.Environment }}_${{ pair.key }}
            displayName: Deployment ${{ parameters.EnvironmentName }} ${{ pair.value }}
            workspace:
              clean: all
            # use a different environment for resource triggers so we can have different approvals
            ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
              environment: Deployment_Dev_${{ parameters.Environment }}
            ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
              environment: Deployment_${{ parameters.Environment }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: ArchiveFiles@2
                      displayName: Archive web app
                      inputs:
                        rootFolderOrFile: $(ArtifactDirectory)/${{ parameters.ArtifactName }}
                        includeRootFolder: false
                        archiveType: zip
                        archiveFile: $(ArtifactDirectory)/${{ parameters.ArtifactName }}.zip
                        replaceExistingArchive: true

                    - task: AzureWebApp@1
                      displayName: Deploy web app
                      inputs:
                        azureSubscription: $(AzureSubscriptionName)
                        appType: webApp
                        appName: $(AzureProductName)-${{ parameters.Environment }}-${{ pair.key }}-app
                        resourceGroupName: $(AzureProductName)-${{ parameters.Environment }}-${{ pair.value }}-rg
                        package: $(ArtifactDirectory)/${{ parameters.ArtifactName }}.zip
                        deploymentMethod: zipDeploy
                        deployToSlotOrASE: false
