stages:
  - stage: Build
    # always build for master except if it is a resource trigger (e.g. already build with the build pipeline)
    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'ResourceTrigger'))
    jobs:
      - job: Build
        workspace:
          clean: all
        steps:
          - template: ../templates/dotnet-publish.yml
            parameters:
              # we don't have any tests yet
              PublishCodeCoverage: false
              PublishProjects: 'src/WebApi/*.csproj'
              PublishArtifactName: Backend
